casino_poker:
    resource: "@CasinoPokerBundle/Resources/config/routing.yml"
    prefix:   /

app_graph:
    resource: "@AppGraphBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
